### ISSUE TITLE
error: 'linux/vmlinux.h' file not found

### ISSUE THREAD

**Issue by TryA9ain** [Esonhugh/sshd_backdoor#4]
sshd_backdoor/pkg/ebpf-c/./common.h:4:10: fatal error: 'linux/vmlinux.h' file not found
#include <linux/vmlinux.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.                                                           
Error: can't execute clang: exit status 1
exit status 1
pkg/generate/compile.go:7: running "go": exit status 1
make: *** [Makefile:29: generate] Error 1

**Comment by Esonhugh** [comment]
vmlinux.h is common file. You can generate like `bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h` and `bpftool` needs to be installed.
put the vmlinux file and make sure that the common.h can locate it.


I put the file under `/usr/include/linux/` folder.

**Comment by TryA9ain** [comment]
> vmlinux.h is common file. You can generate like `bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h` and `bpftool` needs to be installed. put the vmlinux file and make sure that the common.h can locate it.
> 
> I put the file under `/usr/include/linux/` folder.

new error ...

4 errors generated.

Error: can't execute clang: exit status 1

exit status 1

pkg/generate/compile.go:7: running "go": exit status 1

make: *** [Makefile:29: generate] Error 1

<img width="994" alt="image" src="https://user-images.githubusercontent.com/51145610/215674998-6b496f6d-0339-4d6f-bf94-a87889d6584d.png">

**Comment by Esonhugh** [comment]
what's the kernel version? Looks Like a little bit old.

**Comment by Esonhugh** [comment]
Seems Your kernel is not Supported the Ringbuf. And The TASK_COMM_LEN is define as macro const `#define TASK_COMM_LEN 16` in vmlinux.h

**Comment by TryA9ain** [comment]
> Ringbuf

`cat /proc/version`

Linux version 4.18.0-240.1.1.el8_3.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Thu Nov 19 17:20:08 UTC 2020

----------------------------------------------------------------------------------------------------------------------------

┌──(root㉿kali)-[~]
└─# cat /proc/version
Linux version 5.15.0-kali3-amd64 (devel@kali.org) (gcc-11 (Debian 11.2.0-14) 11.2.0, GNU ld (GNU Binutils for Debian) 2.37.90.20220123) #1 SMP Debian 5.15.15-2kali1 (2022-01-31)

**Comment by Esonhugh** [comment]
ringbuf support starts at kernel 5.8 
I delete the ringbuf support (because of unused) with new commit.

> > Ringbuf
> 
> `cat /proc/version`
> 
> Linux version 4.18.0-240.1.1.el8_3.x86_64 ([mockbuild@kbuilder.bsys.centos.org](mailto:mockbuild@kbuilder.bsys.centos.org)) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Thu Nov 19 17:20:08 UTC 2020

Ringbuf support in kernel > 5.8

I delete the ringbuf map in new commit because of unused.

**Comment by Esonhugh** [comment]
And my kali is aarch64. U may need change some IncludePath.

**Comment by TryA9ain** [comment]
> what's the kernel version? Looks Like a little bit old.



> ringbuf support starts at kernel 5.8 I delete the ringbuf support (because of unused) with new commit.
> 
> > > Ringbuf
> > 
> > 
> > `cat /proc/version`
> > Linux version 4.18.0-240.1.1.el8_3.x86_64 ([mockbuild@kbuilder.bsys.centos.org](mailto:mockbuild@kbuilder.bsys.centos.org)) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Thu Nov 19 17:20:08 UTC 2020
> 
> Ringbuf support in kernel > 5.8
> 
> I delete the ringbuf map in new commit because of unused.

now 2 error

/root/sshd_backdoor/pkg/ebpf-c/./openat_syscall.h:21:17: error: use of undeclared identifier 'TASK_COMM_LEN'; did you mean 'TIS_MEM_LEN'?
    char common[TASK_COMM_LEN];
                ^~~~~~~~~~~~~
                TIS_MEM_LEN
/usr/include/linux/vmlinux.h:75862:2: note: 'TIS_MEM_LEN' declared here
        TIS_MEM_LEN = 20480,
        ^
In file included from /root/sshd_backdoor/pkg/ebpf-c/xdp.c:18:
/root/sshd_backdoor/pkg/ebpf-c/./openat_syscall.h:22:38: error: use of undeclared identifier 'TASK_COMM_LEN'; did you mean 'TIS_MEM_LEN'?
    if(bpf_get_current_comm(&common, TASK_COMM_LEN)) {
                                     ^~~~~~~~~~~~~
                                     TIS_MEM_LEN
/usr/include/linux/vmlinux.h:75862:2: note: 'TIS_MEM_LEN' declared here
        TIS_MEM_LEN = 20480,
        ^
2 errors generated.
Error: can't execute clang: exit status 1
exit status 1
pkg/generate/compile.go:7: running "go": exit status 1
make: *** [Makefile:29: generate] Error 1

**Comment by Esonhugh** [comment]
> Seems Your kernel is not Supported the Ringbuf. And The TASK_COMM_LEN is define as macro const `#define TASK_COMM_LEN 16` in vmlinux.h

`#define TASK_COMM_LEN 16`

**Comment by TryA9ain** [comment]
> > 似乎您的内核不支持 Ringbuf。并且 TASK_COMM_LEN`#define TASK_COMM_LEN 16`在 vmlinux.h中定义为宏常量
> 
> `#define TASK_COMM_LEN 16`

111, thank you

**Comment by KrauseBerg** [comment]
> > Seems Your kernel is not Supported the Ringbuf. And The TASK_COMM_LEN is define as macro const `#define TASK_COMM_LEN 16` in vmlinux.h
> 
> `#define TASK_COMM_LEN 16`

4 errors generated.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/43274275/216446472-86875fb0-5a76-4fca-bad2-4aede4d2a1c1.png">


`cat /proc/version`
Linux version 5.4.0-137-generic (buildd@lcy02-amd64-009) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023

**Comment by KrauseBerg** [comment]
Solved by adding `#define BPF_ANY 0` in `vmlinux.h` file

**Comment by Esonhugh** [comment]
> Solved by adding `#define BPF_ANY 0` in `vmlinux.h` file

Great. But It should be defined at vmlinux.h or bpf header files by bpftool automatically when generating.
